# Generated by Django 5.0 on 2023-12-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobProfile',
        ),
        migrations.DeleteModel(
            name='RegistrationProfile',
        ),
    ]
