# Generated by Django 5.0 on 2023-12-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_registrationprofile_user_delete_jobprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_freelancer',
        ),
    ]
