# Generated by Django 5.0 on 2023-12-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='is_freelancer',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
